package com.example.pickleballremotescorer;
import android.app.*; import android.os.*; import android.view.*; import android.widget.*; import java.util.*;
public class MainActivity extends Activity {
 TextView scoreA,scoreB,serveA,serveB,status; int a=0,b=0,team=0,server=1; Handler h=new Handler(Looper.getMainLooper()); boolean pending=false,longDone=false; long downAt=0; Deque<int[]> hist=new ArrayDeque<>();
 final Runnable singlePress=new Runnable(){public void run(){if(pending&&!longDone){pending=false;save();point();}}};
 final Runnable longPress=new Runnable(){public void run(){if(downAt!=0){longDone=true;pending=false;h.removeCallbacks(singlePress);save();switchTeam();}}};
 public void onCreate(Bundle x){super.onCreate(x);setContentView(R.layout.activity_main);scoreA=findViewById(R.id.scoreA);scoreB=findViewById(R.id.scoreB);serveA=findViewById(R.id.serveA);serveB=findViewById(R.id.serveB);status=findViewById(R.id.status);findViewById(R.id.undo).setOnClickListener(v->undo());findViewById(R.id.switchServer).setOnClickListener(v->{save();server=server==1?2:1;update();});findViewById(R.id.switchTeam).setOnClickListener(v->{save();switchTeam();});findViewById(R.id.reset).setOnClickListener(v->{a=b=0;team=0;server=1;hist.clear();update();});update();}
 public boolean dispatchKeyEvent(KeyEvent e){int c=e.getKeyCode();if(c==KeyEvent.KEYCODE_VOLUME_UP||c==KeyEvent.KEYCODE_VOLUME_DOWN||c==KeyEvent.KEYCODE_CAMERA||c==KeyEvent.KEYCODE_ENTER){if(e.getAction()==KeyEvent.ACTION_DOWN){if(e.getRepeatCount()==0){downAt=System.currentTimeMillis();longDone=false;h.postDelayed(longPress,850);}return true;}if(e.getAction()==KeyEvent.ACTION_UP){h.removeCallbacks(longPress);downAt=0;if(longDone){longDone=false;return true;}if(pending){pending=false;h.removeCallbacks(singlePress);save();server=server==1?2:1;update();}else{pending=true;h.postDelayed(singlePress,430);}return true;}}return super.dispatchKeyEvent(e);}
 void save(){hist.push(new int[]{a,b,team,server});} void undo(){if(!hist.isEmpty()){int[]s=hist.pop();a=s[0];b=s[1];team=s[2];server=s[3];update();}}
 void point(){if(team==0)a++;else b++;update();if((a>=11||b>=11)&&Math.abs(a-b)>=2)new AlertDialog.Builder(this).setTitle((a>b?"Team A":"Team B")+" wins!").setMessage(a+" – "+b).setPositiveButton("New Game",(d,w)->{a=b=0;team=0;server=1;hist.clear();update();}).setNegativeButton("Keep Score",null).show();}
 void switchTeam(){team=1-team;server=1;update();}
 void update(){scoreA.setText(""+a);scoreB.setText(""+b);serveA.setText(team==0?"SERVING • "+server:"");serveB.setText(team==1?"SERVING • "+server:"");status.setText("Remote ready • Serving: Team "+(team==0?"A":"B")+" • Server "+server);}
}